services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend/registrations-vue3
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    command: npm run dev
  

  # cypress:
  #   image: cypress/included:13.12.0
  #   working_dir: /app
  #   volumes:
  #     - ./frontend/registrations-vue3:/app
  #   depends_on:
  #     - frontend
  #   environment:
  #     - CYPRESS_BASE_URL=http://frontend:8080
  #   entrypoint: ["npm", "run", "cypress:run"]
