services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    build: ./FRONTEND/vue-project
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND/vue-project:/app
    depends_on:
      - backend
