services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend/registrations-vue3
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    command: npm run dev
  
  frontend-tests:
    build: ./frontend/registrations-vue3
    environment:
      - NODE_ENV=test
    command: npm run test:e2e
    entrypoint: ["sh", "-c"]
    restart: "no"
