services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend/registrations-vue3
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend/registrations-vue3:/app
    environment:
      - NODE_ENV=production
    command: npm run dev
